version: '3.2'

services:

  pulsar:
    image: apachepulsar/pulsar:2.5.2
    ports:
      - "6650:6650"
      - "6651:6651"
      - "8443:8443"
    networks:
      - pulsar
    volumes:
      - type: bind
        source: ./config/certs
        target: /pulsar/certs
    environment:
      - tlsEnabled=true
      - PULSAR_PREFIX_brokerServicePortTls=6651
      - PULSAR_PREFIX_webServicePortTls=8443
      - tlsAllowInsecureConnection=false
      - tlsRequireTrustedClientCertOnConnect=false
      - tlsCertificateFilePath=/pulsar/certs/broker.cert.pem
      - tlsKeyFilePath=/pulsar/certs/broker.key-pk8.pem
      - tlsTrustCertsFilePath=/pulsar/certs/ca.cert.pem
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py ../../pulsar/conf/standalone.conf
      && bin/pulsar standalone"

networks:
  pulsar:
    driver: bridge
